# Generated by Django 4.1.7 on 2023-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0002_alter_user_managers_user_first_name_user_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100, verbose_name="이름"),
        ),
    ]
