# Generated by Django 4.2 on 2023-04-26 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='모임 시작 일시')),
                ('join_deadline', models.DateTimeField(verbose_name='인원 모집 마각 일시')),
                ('place', models.CharField(max_length=30, verbose_name='모임 장소')),
                ('category', models.CharField(max_length=30, verbose_name='모임 유형')),
                ('description', models.TextField(blank=True, default='', verbose_name='추가 정보')),
                ('people_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 인원')),
                ('joined_members', models.ManyToManyField(related_name='joined_matchings', to=settings.AUTH_USER_MODEL, verbose_name='참여 유저')),
            ],
        ),
    ]
