# Generated by Django 4.2 on 2023-04-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_matchings', to=settings.AUTH_USER_MODEL, verbose_name='주최자'),
            preserve_default=False,
        ),
    ]
