# Generated by Django 4.2 on 2023-04-26 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0002_matching_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 일시'),
            preserve_default=False,
        ),
    ]
